server:
  port: "8081"
  mode: "debug" # debug, release

database:
  host: "localhost"
  port: 5440
  user: "${VOKZAL_DB_USER}"
  password: "${VOKZAL_DB_PASSWORD}"
  dbname: "vokzal"
  sslmode: "disable"

jwt:
  secret: "${VOKZAL_AUTH_JWT_SECRET}"
  issuer: "vokzal.tech"
  access_expiration: "24h"
  refresh_expiration: "168h" # 7 дней

logger:
  level: "debug" # debug, info, warn, error
