server:
  port: "8083"
  mode: "debug"

database:
  host: "localhost"
  port: 5440
  user: "${VOKZAL_DB_USER}"
  password: "${VOKZAL_DB_PASSWORD}"
  dbname: "vokzal"
  sslmode: "disable"

jwt:
  secret: "${VOKZAL_TICKET_JWT_SECRET}"
  issuer: "vokzal.tech"

nats:
  url: "${VOKZAL_NATS_URL}"
  user: "${VOKZAL_NATS_USER}"
  password: "${VOKZAL_NATS_PASSWORD}"

logger:
  level: "debug"

business:
  refund_penalty:
    over_24_hours: 0.10    # 10% штраф если > 24 часов до отправления
    between_12_24: 0.20    # 20% штраф если 12-24 часа до отправления
    under_12_hours: 0.30   # 30% штраф если < 12 часов до отправления
