version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - gosec
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gocyclo
    - godot
    - goprintffuncname
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      enable:
        - shadow
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
    revive:
      rules:
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
        - name: var-naming
          severity: warning
    gosec:
      excludes:
        - G104 # Audit errors not checked
        - G304 # File path provided as taint input
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 75
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
      # Exclude known linters from partially hard-vendored code
      - path: vendor/
        linters:
          - all
      # CRUD repositories and services have similar patterns by design
      - path: services/schedule/internal/repository/
        linters:
          - dupl
      - path: services/schedule/internal/service/
        linters:
          - dupl

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/vokzal-tech

issues:
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true
