server:
  port: "8085"
  mode: "debug"

database:
  host: "localhost"
  port: 5440
  user: "${VOKZAL_DB_USER}"
  password: "${VOKZAL_DB_PASSWORD}"
  dbname: "vokzal"
  sslmode: "disable"

nats:
  url: "${VOKZAL_NATS_URL}"
  user: "${VOKZAL_NATS_USER}"
  password: "${VOKZAL_NATS_PASSWORD}"

logger:
  level: "debug"

tinkoff:
  terminal_key: "${VOKZAL_TINKOFF_TERMINAL_KEY}"
  password: "${VOKZAL_TINKOFF_PASSWORD}"
  api_url: "https://securepay.tinkoff.ru/v2"

sbp:
  merchant_id: "${VOKZAL_SBP_MERCHANT_ID}"
  api_key: "${VOKZAL_SBP_API_KEY}"
  api_url: "https://api.sbp.nspk.ru"
