server:
  port: "8087"
  mode: "debug"

database:
  host: "localhost"
  port: 5440
  user: "${VOKZAL_DB_USER}"
  password: "${VOKZAL_DB_PASSWORD}"
  dbname: "vokzal"
  sslmode: "disable"

nats:
  url: "${VOKZAL_NATS_URL}"
  user: "${VOKZAL_NATS_USER}"
  password: "${VOKZAL_NATS_PASSWORD}"

logger:
  level: "debug"

sms:
  api_id: "${VOKZAL_SMS_API_ID}"
  url: "https://sms.ru/sms/send"

email:
  smtp_host: "smtp.yandex.ru"
  smtp_port: 587
  username: "${VOKZAL_EMAIL_USERNAME}"
  password: "${VOKZAL_EMAIL_PASSWORD}"
  from: "Вокзал.ТЕХ <noreply@vokzal.tech>"

telegram:
  bot_token: "${VOKZAL_TELEGRAM_BOT_TOKEN}"
  webhook_url: "https://api.vokzal.tech/v1/notify/telegram/webhook"

local_agent:
  url: "http://localhost:8081"
